# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the IBS kernel
#'
#' @param \code{z} A SNP matrix of size \code{n x M}. Here \code{n} is the
#'                   number of subjects and \code{M} is the number of SNPs. Each
#'                   entry of \code{z} should be 0, 1 or 2 denoting the minor
#'                   allele frequency.
#' @export
IBSKernel <- function(z) {
    .Call('_RobKAT_IBSKernel', PACKAGE = 'RobKAT', z)
}

